# /// script
# requires-python = ">=3.9"
# dependencies = []
# ///
"""Emit the LaTeX body of tab:offsetcost for the fifteen-column corpus.

    uv run figures/tab_offsetcost_suite.py                       # rows to stdout
    uv run figures/tab_offsetcost_suite.py --suite-id paper-20260821

WHAT THIS CAN AND CANNOT DERIVE, and why the table has holes.

The sidecar is one u64 output offset per batch of 128 codes. Two of the table's three
quantities are therefore arithmetic on committed suite data, and one is not:

  Batches       ceil(total_tokens / 128). Confirmed against results/b300-campaign-0717/
                offset_cost.jsonl, where total_tokens/n_batches = 127.99 on every row.
  Raw           8 * batches. A constant 3.125% of the code stream, so it gets no column.
  Stored        the sidecar as actually written. Produced by the CPU-only ONPAIR_OFFSET_COST
                path (no cuda feature; results/offset-reshape-cost-laptop/ ran on a laptop),
                which emits offset_compressed_bytes. Not reproducible by arithmetic: in the
                0717 campaign it landed at 0.13-0.23x of raw, varying by column. Prints `--`.
  Regeneration  the throughput lost rebuilding offsets on the device instead of reading them.
                This one is a decode-path measurement and does need a GPU. Prints `--`.

THE 2026-08-21 SUITE HAS NO OFFSETS ARM. Its stages are MATERIALIZE GRID DE ZSTD FSST LADDER,
none of which writes a sidecar or times regeneration. The sidecar half needs only a CPU pass at
the campaign rev; see docs/notes/2026-08-22-offsetcost-table-prep.md in the paper repo.

DENOMINATOR. `Stored` has to be a percentage of something, and the two candidates are not the
same quantity. gpu.compressed_bytes is codes widened to u16, exactly 2 B/code, and is what
tab:datasets' Ratio and Section 5 use. in_memory_bytes is the packed representation, and is
what the 0717 sidecar percentages were against (it matches that campaign's compressed_bytes to
0.1-1.2% on the overlapping columns). Settle this before filling the column.

MISSING CELLS PRINT `--`, following tab_datasets_suite.py. A row that vanishes is how a
reader comes to believe the corpus is smaller than it is.
"""
import argparse
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import suite as S  # noqa: E402

BATCH_CODES = 128          # one warp's batch; Section 3 states it, 0717 data confirms 127.99


def batches(c):
    """Sidecar entries: one output offset per batch of BATCH_CODES codes."""
    t = ((c or {}).get("gpu") or {}).get("total_tokens")
    return math.ceil(t / BATCH_CODES) if t else None


def raw_pct(c):
    """Raw u64 sidecar as a percentage of the bytes the GPU reads."""
    n = batches(c)
    comp = ((c or {}).get("gpu") or {}).get("compressed_bytes")
    return (100.0 * 8 * n / comp) if (n and comp) else None


def fmt_int(v):
    return "--" if v is None else f"{v:,}".replace(",", "\\,")


def fmt(v, spec, suffix=""):
    return "--" if v is None else format(v, spec) + suffix


def row(label, c12, c16):
    """Batches | Stored | Regeneration, per preset.

    No Raw column: it is 8/(128*2) = 3.125% for every column and both presets, because the
    suite stores codes as u16 (measured 3.108-3.125% over all 30 cells). A constant belongs
    in one sentence of prose, not in thirty table cells."""
    cells = [
        fmt_int(batches(c12)), "--", "--",
        "",
        fmt_int(batches(c16)), "--", "--",
    ]
    return f"{label} & " + " & ".join(cells) + " \\\\"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--suite-id", default=None)
    ap.add_argument("--chip", default="b300")
    a = ap.parse_args()

    root = S.latest_root(a.suite_id)
    if root is None:
        sys.exit("no results/suite-* directory found")
    cs = S.cells(root, a.chip, "boost", "onpair")

    out, missing = [], []
    for group, rows in (("real", S.REAL), ("gen", S.GEN)):
        for label, ds, col in rows:
            c12, c16 = cs.get((ds, col, 12)), cs.get((ds, col, 16))
            for name, cell in (("OnPair-12", c12), ("OnPair-16", c16)):
                if cell is None:
                    missing.append(f"{ds}/{col} {name}")
            out.append(row(label, c12, c16))
        if group == "real":
            out.append("\\midrule")

    print(f"% GENERATED by figures/tab_offsetcost_suite.py from results/{root.name}/{a.chip}")
    print(f"% Batches = ceil(gpu.total_tokens/{BATCH_CODES}). Raw sidecar is a constant 3.125% of")
    print("% the code stream (u16 codes), so it is stated in prose rather than given a column.")
    print("% Stored and Regeneration are `--`: no offsets arm in this suite. See the docstring.")
    print("\n".join(out))

    if missing:
        print(f"\n% INCOMPLETE: {len(missing)} cells absent -> printed as --", file=sys.stderr)
        for m in missing[:10]:
            print(f"%   {m}", file=sys.stderr)
    else:
        print("\n% all 15 columns x 2 presets present for the derived columns", file=sys.stderr)
    print("% Stored and Regeneration need a run; they are not in any committed suite leg.",
          file=sys.stderr)


if __name__ == "__main__":
    main()
